# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Glenn Roberts"
description: > # this means to ignore newlines until "email:"
   Tech, Startups, Digital Nomad Life

email: glenn@siyelo.com
#blog logo
logo: "/assets/images/gr_logo.png"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Glenn Roberts'
author: 'Glenn Roberts'
author_bio: 'Technologist, Entrepreneur, Partner at Siyelo'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://glenn-roberts.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/glennrob
    desc: Follow @glennrob
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon: reddit
    url:  https://reddit.com/r/glennrob
    desc: /r/glennrob
    share_url: https://www.reddit.com/submit
    share_title: ?title=
    share_link: "&amp;url="
  - icon:	github
    url:	https://github.com/glennr
    desc:	Fork me on github